import puppeteer from "puppeteer";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const OUT = "D:\\DSH工作区\\哥伦比娅生日会\\venue\\";
const b = await puppeteer.launch({ headless: "new", args: ["--no-sandbox"], protocolTimeout: 240000 });
const p = await b.newPage();
await p.setViewport({ width: 1280, height: 720 });
await p.goto("http://localhost:5173/venue.html", { waitUntil: "networkidle2", timeout: 90000 });
await sleep(3500);
await p.evaluate(() => localStorage.clear());
await p.reload({ waitUntil: "networkidle2", timeout: 90000 });
await sleep(6500);
const info = await p.evaluate(async () => {
  const s = window.__venueScene;
  const { QUESTS } = await import("/src/quests.js");
  QUESTS.forEach((q) => { s.quests.data.states[q.id] = "completed"; });
  s.scenes.load("venue", { tileX: 20, tileY: 18 }, true);
  await new Promise((r) => setTimeout(r, 1200));
  s.maybeStartParty();
  await new Promise((r) => setTimeout(r, 1500));
  s.cameras.main.stopFollow();
  s.cameras.main.setZoom(0.52);
  s.cameras.main.centerOn(1280, 700);
  return { party: s.party, objs: s.partyObjs.length, zoom: s.cameras.main.zoom, wvY: Math.round(s.cameras.main.worldView.y) };
});
console.log(JSON.stringify(info));
await sleep(700);
await p.screenshot({ path: OUT + "_party_overview.png" });
await b.close();
console.log("done");
